spring:
  application:
    name: currency-conversion

  sleuth:
    sampler:
      probability: 1.0 
  
 

  config:
    import:
    - "optional:configserver:"


server:  port: 8100       
  
eureka:  client:    service-url:      defaultZone:  http://localhost:8761/eureka
  
  
  